---
title: "Tweet Disagreement Handling"
output: html_notebook
---

```{r}
library(mongolite)
library(tidyverse)
library(dplyr)
library(irr)
library(jsonlite)
library(emojifont)
library(schoolmath)
```

```{r}
options(max.print=999999)

#import MongoDB collection into R
db <- mongo(
  collection = "all",
  db = "analysis",
  url = "mongodb://localhost:27017/",
  verbose = FALSE,
  options = ssl_options()
)


#count observations
db$count()


# put environment into proper dataset - makes it easy to get an overview of nested table
# remove(annotations)
annotations <- db$find('{}')

# Flatten table
annotations9 <- annotations %>% flatten()
Sys.setlocale(category="LC_ALL", locale = "en_US.UTF-8")

#assignfinalannotationcolumns
annotations9$finalannotationcontentcategory = NA
annotations9$finalannotationsentiment = NA
annotations9$finalannotationgender = NA
glimpse(annotations9)

#Resolve disagreement in gender
i=0

for (i in 1:(nrow(annotations9))) {
  if(annotations9[i, 89] == annotations9[i, 102]) {
    annotations9$finalannotationgender[i] <- annotations9[i, 89]
  } else
    annotations9$finalannotationgender[i] <- "unknown"
} 

print(annotations9$finalannotationgender)
```


```{r}
#Convert sentiment into numbers first labeler
k=0

for (k in 1:(nrow(annotations9))) {
  if(annotations9[k, 88] == "Very Negative") {
    annotations9[k, 88]<- -2
  } else if (annotations9[k, 88] == "Negative") {
    annotations9[k, 88]<- -1
  } else if (annotations9[k, 88] == "Neutral") {
    annotations9[k, 88]<- 0
  } else if (annotations9[k, 88] == "Positive") {
    annotations9[k, 88]<- 1
  } else
    annotations9[k, 88]<- 2
}

#Convert sentiment into numbers second labeler
j=0

for (j in 1:(nrow(annotations9))) {
  if(annotations9[j, 101] == "Very Negative") {
    annotations9[j, 101]<- -2
  } else if (annotations9[j, 101] == "Negative") {
    annotations9[j, 101]<- -1
  } else if (annotations9[j, 101] == "Neutral") {
    annotations9[j, 101]<- 0
  } else if (annotations9[j, 101] == "Positive") {
    annotations9[j, 101]<- 1
  } else
    annotations9[j, 101]<- 2
}

#Convert characters into numeric
annotations9[, 88] <- as.numeric(annotations9[, 88])
annotations9[, 101] <- as.numeric(annotations9[, 101])

annotations9[1, 101] <- 0
#Resolve disagreement in sentiment
m=0

for (m in 1:(nrow(annotations9))) {
  if(annotations9[m, 88] == annotations9[m, 101]) {
    annotations9$finalannotationsentiment[m] <- annotations9[m, 88]
  } else if (((annotations9[m, 88] + annotations9[m, 101])/2) - floor((annotations9[m, 88] + annotations9[m, 101])/2) == 0) {
    annotations9$finalannotationsentiment[m] <- (annotations9[m, 88] + annotations9[m, 101])/2
  } else if (is.negative((annotations9[m, 88] + annotations9[m, 101])/2) == TRUE) {
    annotations9$finalannotationsentiment[m] <- trunc(((annotations9[m, 88] + annotations9[m, 101])/2),digits=0)
  } else
    annotations9$finalannotationsentiment[m] <- floor((annotations9[m, 88] + annotations9[m, 101])/2)
} 

print(annotations9$finalannotationsentiment)
```


```{r}
#Resolve disagreement in content
n=0

for (n in 1:(nrow(annotations9))) {
#BR & BR = BR
  if(annotations9[n, 103] == annotations9[n, 90] & annotations9[n, 90] == TRUE) {
    annotations9$finalannotationcontentcategory[n] <- "BugReport"
  } 
  
#SR & SR = SR
  else if (annotations9[n, 104] == annotations9[n, 91] & annotations9[n, 91] == TRUE) {
    annotations9$finalannotationcontentcategory[n] <- "SupportRequest"
  } 
  
#FR & FR = FR
  else if (annotations9[n, 105] == annotations9[n, 92] & annotations9[n, 92] == TRUE) {
    annotations9$finalannotationcontentcategory[n] <- "FeatureRequest"
  } 
  
#Anno2_BR == Anno1_BR & Anno1_BR == TRUE & Anno2_FR == Anno1_FR & Anno1_FR == TRUE
  else if (annotations9[n, 103] == annotations9[n, 90] & annotations9[n, 90] == TRUE & annotations9[n, 105] == annotations9[n, 92] & annotations9[n, 92] == TRUE ) {
      annotations9$finalannotationcontentcategory[n] <- "BugReportFeatureRequest"
  }
#Anno2_BR == TRUE & Anno1_SR == TRUE | Anno2_SR == TRUE & Anno1_BR == TRUE
  else if (annotations9[n, 103] == TRUE & annotations9[n, 91] == TRUE | annotations9[n, 104] == TRUE & annotations9[n, 90] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "BugReport"
  }
  
#Anno2_BR == TRUE & Anno1_OTH == TRUE | Anno2_OTH == TRUE & Anno1_BR == TRUE
  else if (annotations9[n, 103] == TRUE & annotations9[n, 96] == TRUE | annotations9[n, 109] == TRUE & annotations9[n, 90] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "BugReport"
  }
  
#Anno2_BR == TRUE & Anno1_NOISE == TRUE | Anno2_NOISE == TRUE & Anno1_BR == TRUE
  else if (annotations9[n, 103] == TRUE & annotations9[n, 95] == TRUE | annotations9[n, 108] == TRUE & annotations9[n, 90] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "BugReport"
  }
  
#Anno2_FR == TRUE & Anno1_SR == TRUE | Anno2_SR == TRUE & Anno1_FR == TRUE
  else if (annotations9[n, 105] == TRUE & annotations9[n, 91] == TRUE | annotations9[n, 104] == TRUE & annotations9[n, 92] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "FeatureRequest"
  }
  
#Anno2_FR == TRUE & Anno1_OTH == TRUE | Anno2_OTH == TRUE & Anno1_FR == TRUE
  else if (annotations9[n, 105] == TRUE & annotations9[n, 96] == TRUE | annotations9[n, 109] == TRUE & annotations9[n, 92] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "FeatureRequest"
  }

#Anno2_FR == TRUE & Anno1_NOISE == TRUE | Anno2_NOISE == TRUE & Anno1_FR == TRUE
  else if (annotations9[n, 105] == TRUE & annotations9[n, 95] == TRUE | annotations9[n, 108] == TRUE & annotations9[n, 92] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "FeatureRequest"
  }
  

#Anno2_SR == TRUE & Anno1_OTH == TRUE | Anno2_OTH == TRUE & Anno1_SR == TRUE
  else if (annotations9[n, 104] == TRUE & annotations9[n, 96] == TRUE | annotations9[n, 109] == TRUE & annotations9[n, 91] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "SupportRequest"
  }
  
#Anno2_SR == TRUE & Anno1_NOISE == TRUE | Anno2_NOISE == TRUE & Anno1_SR == TRUE
  else if (annotations9[n, 104] == TRUE & annotations9[n, 95] == TRUE | annotations9[n, 108] == TRUE & annotations9[n, 91] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "SupportRequest"
  }
  
#Anno2_OTH == TRUE & Anno1_NOISE == TRUE | Anno2_NOISE == TRUE & Anno1_OTH == TRUE
  else if (annotations9[n, 109] == TRUE & annotations9[n, 95] == TRUE | annotations9[n, 108] == TRUE & annotations9[n, 96] == TRUE)
   {
      annotations9$finalannotationcontentcategory[n] <- "Other"
  }
  
  else if (annotations9[n, 108] == annotations9[n, 95] & annotations9[n, 95] == TRUE) {
    annotations9$finalannotationcontentcategory[n] <- "Noise"
  } 
  
  else if (annotations9[n, 109] == annotations9[n, 96] & annotations9[n, 96] == TRUE) {
    annotations9$finalannotationcontentcategory[n] <- "Other"
  } 
}

print(annotations9$finalannotationcontentcategory)
```


```{r}
#bind finalannotationssets
finalannotationsfr <-  annotations9
finalannotationsfr <- rbind(finalannotationsfr)

glimpse(finalannotationsfr)
```


```{r}
#create mongodb dataset
my_collection = mongo(collection = "final1", db = "analysis") # create connection, database and collection
my_collection$insert(finalannotationsfr)


```

